#!/bin/bash

### BEGIN INIT INFO
# Provides:		wireless-pi
# Required-Start:
# Required-Stop:
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description:    wireless-pi process
### END INIT INFO

set -e
# start and stop wireless-pi process
#source the .bashrc from pi which should contains
#nodejs executable
. /home/pi/.bashrc

#utility functions
. /lib/lsb/init-functions

nodebin=`which node`
wirelessPiDir=###WIRELESSPIDIR###

case "$1" in
  start)
	log_daemon_msg "Starting wireless-pi process" || true
	start-stop-daemon -m --start --quiet -b --pidfile /var/run/wireless-pi-init.pid --exec $nodebin $wirelessPiDir
	;;
  stop)
	log_daemon_msg "Stopping wireless-pi process" || true
	start-stop-daemon -m --stop --quiet --pidfile /var/run/wireless-pi-init.pid
	;;

  restart)
	log_daemon_msg "Restarting wireless-pi" || true
	start-stop-daemon -m --stop --quiet --retry 30 --pidfile /var/run/wireless-pi-init.pid
	start-stop-daemon -m --start --quiet -b --pidfile /var/run/wireless-pi-init.pid --exec $nodebin $wirelessPiDir
	;;

  status)
	status_of_proc -p /var/run/wireless-pi-init.pid $nodebin wireless-pi && exit 0 || exit $?
	;;

  *)
	log_action_msg "Usage: /etc/init.d/wireless-pi {start|stop|restart|status}" || true
	exit 1
esac

exit 0
